#default config
info:
  description: Spring Cloud Config Repo
  url: https://github.com:peerlesszh/wzh-config-repo

---
spring:
  profiles: production
properties:
  option1: Test staging value1

---
spring:
  profiles: docker
  endpoints:
    restart: enabled
